export const CREATE_RECIPE = 'CREATE_RECIPE';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const COPY_RECIPE = 'COPY_RECIPE';

export const FILTER_INGREDIENTS_GRID = 'FILTER_INGREDIENTS_GRID';
export const SORT_INGREDIENTS_GRID = 'SORT_INGREDIENTS_GRID';